// Code generated by "stringer -type GrammarKind"; DO NOT EDIT.

package syntaxa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GToken-1]
	_ = x[GConcat-2]
	_ = x[GChoice-3]
	_ = x[GRepeat-4]
	_ = x[GOptional-5]
	_ = x[GEpsilon-6]
	_ = x[GNest-7]
	_ = x[GReference-8]
}

const _GrammarKind_name = "GTokenGConcatGChoiceGRepeatGOptionalGEpsilonGNestGReference"

var _GrammarKind_index = [...]uint8{0, 6, 13, 20, 27, 36, 44, 49, 59}

func (i GrammarKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_GrammarKind_index)-1 {
		return "GrammarKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GrammarKind_name[_GrammarKind_index[idx]:_GrammarKind_index[idx+1]]
}
