package syntaxa

import (
	"strconv"
	"strings"
)

/*
GrammarKind denotes the algebraic operation represented by a grammar node.

The grammar IR is intentionally minimal and purely structural. Each kind
corresponds to a fundamental grammar combinator found in EBNF/PEG-style
grammars. Optional recovery metadata (RecoveryTokens, NoConsumeOnRecoveryTokens)
may be set on rule-root nodes for tooling and introspection; execution semantics
otherwise live in the parser engine.

Kinds:

  - GToken
    Atomic terminal symbol. Matches exactly one lexer token.

  - GConcat
    Sequential composition. All child grammars must match in order.

  - GChoice
    Alternation (union). Exactly one child grammar must match.

  - GRepeat
    Repetition operator. The single child grammar is matched multiple
    times according to Min/Max bounds.

  - GOptional
    Optional operator. Equivalent to GRepeat with Min=0 and Max=1,
    but preserved explicitly for clarity and tooling.

  - GEpsilon
    Empty production. Always succeeds without consuming input.

This algebra is closed and intentionally small. Any higher-level grammar
constructs (lists, blocks, separators, precedence rules, etc.) must compile
down into these primitives rather than extending the IR.

Execution semantics, error recovery, AST construction, and contextual logic
are handled by the parser engine, not by the grammar IR itself.
*/
//go:generate stringer -type GrammarKind
type GrammarKind uint8

const (
	GToken GrammarKind = iota + 1
	GConcat
	GChoice
	GRepeat
	GOptional
	GEpsilon
	GNest
	GReference
)

/*
RuleLabel is an optional human-readable label for a grammar rule.

Used for diagnostics and tooling; the semantic type of a rule is GrammarLabel.
*/
type RuleLabel string

/*
GrammarLabel identifies the kind of production (e.g. PATTERN CHAR LITERAL, LEX RULE).

Semantic type; may appear on multiple nodes. Used for configuration, debug, and as the
Rules map key for context-boundary nodes (where it must be unique).
*/
type GrammarLabel string

/*
GrammarKey uniquely identifies a grammar node instance (topological address).

Derived from NodePath via XXH3 hash during package production. Used for 1:1 maps and
DAG traversal. Zero until set by ProducePackage.
*/
type GrammarKey uint64

/*
NodePath is a dot-separated path from the rule root to a node (e.g. "0", "0.1", "0.2.0").

Generated by FinalizeNodePaths and used as part of NodeKey for analysis (Nullable, First, Follow).
*/
type NodePath string

/*
Grammar represents a node in the declarative grammar intermediate
representation.

The grammar forms a tree of composable combinators describing the syntactic
structure of a language. It is intentionally free of execution behavior and
serves as a canonical, introspectable description of the language grammar.

Field semantics depend on Kind:

  - GToken
    Token holds the terminal token value to be matched.
    Children, Min, and Max are unused.

  - GConcat, GChoice
    Children contains the ordered sub-grammars.
    Token, Min, and Max are unused.

  - GRepeat
    Children must contain exactly one grammar node (the repeated body).
    Min specifies the minimum number of repetitions.
    Max specifies the maximum number of repetitions.

  - nil indicates unbounded repetition.

  - GOptional
    Children must contain exactly one grammar node.
    Token, Min, and Max are unused.

  - GEpsilon
    Represents the empty production.
    All other fields are unused.

  - GNest
    OpenToken and CloseToken hold the bracket terminals; Children holds exactly one body grammar.
    Min and Max are unused.

  - Common
    GrammarLabel identifies the kind of production. GrammarKey is set from NodePath during package production. RuleLabel is optional. NodePath is filled by FinalizeNodePaths.

  - Output (optional)
    OutputNodeKind, when set, is the LST node kind (TNodeKind) produced when this grammar node is the root of a rule. Used for introspection and tooling.

  - Recovery (optional, for rule-root nodes)
    RecoveryTokens and NoConsumeOnRecoveryTokens describe the recovery boundaries for the rule
    that uses this node as its root. When set, the engine resyncs at those tokens on FailureError;
    NoConsumeOnRecoveryTokens are sync points where the token is left in the stream for the parent.
    Populated by ParserRuleCreate when a rule is created with this grammar.

Invariants:

  - GrammarKind determines which fields are semantically valid.
  - No grammar node may contain execution logic beyond optional recovery metadata.
  - Higher-level constructs must be expressed by composition, not by adding
    new GrammarKind values or special-case fields.

This structure enables grammar introspection, transformation, visualization,
pattern derivation, and parser execution from a single authoritative grammar
definition.
*/
type Grammar[TToken, TNodeKind comparable] struct {
	GrammarLabel GrammarLabel
	GrammarKey   GrammarKey

	/* Kind defines the grammar combinator represented by this node. */
	Kind GrammarKind

	/* Token is the terminal symbol matched by GToken nodes. */
	Token TToken

	OpenToken  *TToken
	CloseToken *TToken

	/* Children holds sub-grammars for composite operators (Concat, Choice, Repeat, Optional). */
	Children []*Grammar[TToken, TNodeKind]

	/* Min is the minimum repetition count for GRepeat nodes. */
	Min int

	/* Max is the maximum repetition count for GRepeat nodes. Nil denotes unbounded repetition. */
	Max *int

	RuleLabel RuleLabel

	/* NodePath is assigned by FinalizeNodePaths; used as the key for analysis maps. */
	NodePath *NodePath

	/* IsContextBoundary is true only for the root node of a named production (e.g. from Rule.Root). Used by collectAll to populate the Rules map. */
	IsContextBoundary bool

	/*
		OutputNodeKind, when non-nil, is the LST node kind produced when this grammar node is the root of a rule.
		Used for introspection and tooling; execution uses the rule's contract.
	*/
	OutputNodeKind *TNodeKind

	/*
		RecoveryTokens are sync tokens at which the engine resyncs on FailureError (consumes until one is seen).
		Set on the rule-root grammar by ParserRuleCreate. Nil when not applicable.
	*/
	RecoveryTokens []TToken

	/*
		NoConsumeOnRecoveryTokens are sync tokens at which recovery does not consume (token left in stream for parent).
		Set on the rule-root grammar by ParserRuleCreate. Nil when not applicable.
	*/
	NoConsumeOnRecoveryTokens []TToken

	ReferenceTarget GrammarLabel

	/*
		ResolvedReference is set during ProducePackage for GReference nodes to the referenced rule root.
		Used by the grammar walker so Walk/WalkPre/WalkPost traverse into the referenced production.
	*/
	ResolvedReference *Grammar[TToken, TNodeKind]
}

/*
FinalizeNodePaths assigns a unique NodePath to each node in the grammar tree.

Paths are dot-separated indices from the root (e.g. "0", "0.1", "0.2.0").
Idempotent: if NodePath is already set, the subtree is skipped.
Call this once before producing a grammar package or running analysis.
*/
func (g *Grammar[TToken, TNodeKind]) FinalizeNodePaths() {
	if g == nil {
		return
	}

	if g.NodePath != nil {
		return
	}

	fillForGrammar(g, "0")
}

func fillForGrammar[TToken, TNodeKind comparable](g *Grammar[TToken, TNodeKind], current string) {
	if g == nil || g.NodePath != nil {
		return
	}

	p := NodePath(current)
	g.NodePath = &p

	if len(g.Children) == 0 {
		return
	}

	traverseChildrenPaths(g.Children, current)
}

func traverseChildrenPaths[TToken, TNodeKind comparable](children []*Grammar[TToken, TNodeKind], current string) {
	prefix := current + "."

	var sb strings.Builder
	sb.Grow(len(prefix) + 20)

	for i, child := range children {
		if child == nil {
			continue
		}

		sb.Reset()
		sb.WriteString(prefix)
		sb.WriteString(strconv.Itoa(i))

		fillForGrammar(child, sb.String())
	}
}

/*
MarkAsContextBoundary marks the grammar node as the root of a named production.

Called by the rule factory for nodes created by Rule.Root. collectAll uses this to decide which nodes to add to the Rules map.
*/
func MarkAsContextBoundary[TToken, TNodeKind comparable](g *Grammar[TToken, TNodeKind]) {
	if g != nil {
		g.IsContextBoundary = true
	}
}

/*
Token constructs an atomic terminal grammar node that matches exactly one token.
*/
func Token[TToken, TNodeKind comparable](label GrammarLabel, tok TToken) *Grammar[TToken, TNodeKind] {
	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GToken,
		Token:        tok,
	}
}

/*
Concat constructs a sequential composition of grammar nodes.

All children must match in order for the production to succeed.
At least one child must be provided.
*/
func Concat[TToken, TNodeKind comparable](label GrammarLabel, children ...*Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	if len(children) == 0 {
		panic("Concat: at least one child grammar required")
	}

	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GConcat,
		Children:     children,
	}
}

/*
Nest constructs a bracketed grammar node that matches openToken, then body, then closeToken.

Use cases:
- Parenthesized expressions: ( expr )
- Block delimiters: { stmt* }
- Quote-enclosed strings: " ... "
- Any construct with balanced open/close terminals

Time complexity: O(1)
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- OpenToken and CloseToken are stored as pointers to the given token values

Edge cases:
- Panics if body is nil
*/
func Nest[TToken, TNodeKind comparable](label GrammarLabel, openToken TToken, closeToken TToken, body *Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GNest,
		Children:     []*Grammar[TToken, TNodeKind]{body},
		OpenToken:    &openToken,
		CloseToken:   &closeToken,
	}
}

/*
Choice constructs an alternation between grammar nodes.

Exactly one of the children must match.
At least one child must be provided.
*/
func Choice[TToken, TNodeKind comparable](label GrammarLabel, children ...*Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	if len(children) == 0 {
		panic("Choice: at least one child grammar required")
	}

	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GChoice,
		Children:     children,
	}
}

/*
Repeat constructs a bounded or unbounded repetition grammar.

The body grammar is repeated between min and max times.

If max is nil, repetition is unbounded.

Invariants:
  - body must be non-nil
  - min must be >= 0
  - if max != nil, *max must be >= min
*/
func Repeat[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind], min int, max *int) *Grammar[TToken, TNodeKind] {
	if body == nil {
		panic("Repeat: body grammar must not be nil")
	}
	if min < 0 {
		panic("Repeat: min must be >= 0")
	}
	if max != nil && *max < min {
		panic("Repeat: max must be >= min")
	}

	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GRepeat,
		Children:     []*Grammar[TToken, TNodeKind]{body},
		Min:          min,
		Max:          max,
	}
}

/*
Optional constructs an optional grammar node.

Equivalent to Repeat(body, 0, 1) but preserved explicitly for semantic clarity.
*/
func Optional[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	if body == nil {
		panic("Optional: body grammar must not be nil")
	}

	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GOptional,
		Children:     []*Grammar[TToken, TNodeKind]{body},
	}
}

/*
Epsilon constructs an empty production grammar node.

This always succeeds without consuming input.
*/
func Epsilon[TToken, TNodeKind comparable](label GrammarLabel) *Grammar[TToken, TNodeKind] {
	return &Grammar[TToken, TNodeKind]{
		GrammarLabel: label,
		Kind:         GEpsilon,
	}
}

/*
ZeroOrMore constructs an unbounded repetition with minimum 0.

Equivalent to Repeat(id, body, 0, nil). Matches the body zero or more times (Kleene star).

Use cases:
- Optional lists: item*
- Trailing separators: (elem ("," elem)*)
- Skippable whitespace or comments

Time complexity: O(1) for construction; matching is O(n) in input length
Space complexity: O(1)

Prerequisites:
- body must be non-nil (delegates to Repeat, which panics if body is nil)

Edge cases:
- Can succeed without consuming input (zero repetitions)
*/
func ZeroOrMore[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	return Repeat(label, body, 0, nil)
}

/*
OneOrMore constructs an unbounded repetition with minimum 1.

Equivalent to Repeat(id, body, 1, nil). Matches the body one or more times (positive closure).

Use cases:
- Non-empty lists: item+
- Required sequences: digit+
- At least one occurrence of a sub-grammar

Time complexity: O(1) for construction; matching is O(n) in input length
Space complexity: O(1)

Prerequisites:
- body must be non-nil (delegates to Repeat, which panics if body is nil)

Edge cases:
- Fails if no occurrence of body matches (unlike ZeroOrMore)
*/
func OneOrMore[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind]) *Grammar[TToken, TNodeKind] {
	return Repeat(label, body, 1, nil)
}

/*
Exactly constructs a repetition that must occur exactly n times.

Equivalent to Repeat(id, body, n, &n). The body must match precisely n times.

Use cases:
- Fixed-width fields: exactly 4 digits for a year
- Tuple-like structures: (a, b, c)
- Repetition with both lower and upper bound equal

Time complexity: O(1) for construction; matching is O(n) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- n must be >= 0 (Repeat enforces min >= 0 and max >= min)

Edge cases:
- Panics if body is nil or n < 0 (via Repeat)
- Fails if fewer or more than n matches occur
*/
func Exactly[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind], n int) *Grammar[TToken, TNodeKind] {
	max := n
	return Repeat(label, body, n, &max)
}

/*
AtMost constructs a repetition with no minimum and a fixed maximum.

Equivalent to Repeat(id, body, 0, &max). Matches the body zero up to max times inclusive.

Use cases:
- Bounded optional lists: at most N items
- Length-limited sequences: up to 8 hex digits
- Cap on repetition to avoid runaway matching

Time complexity: O(1) for construction; matching is O(max) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- max must be >= 0 (Repeat requires max >= min; min is 0)

Edge cases:
- Panics if body is nil or max < 0 (via Repeat)
- Succeeds with zero matches; fails only if more than max matches would be required
*/
func AtMost[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind], max int) *Grammar[TToken, TNodeKind] {
	return Repeat(label, body, 0, &max)
}

/*
Between constructs a repetition bounded inclusively between min and max.

Equivalent to Repeat(id, body, min, &max). The body must match at least min times and at most max times.

Use cases:
- Bounded lists: between 1 and 10 items
- Length range constraints: 2 to 4 hex digits
- Repetition with both lower and upper bounds

Time complexity: O(1) for construction; matching is O(max) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- min must be >= 0
- max must be >= min

Edge cases:
- Panics if body is nil, min < 0, or max < min (via Repeat)
- Fails if fewer than min or more than max matches occur
*/
func Between[TToken, TNodeKind comparable](label GrammarLabel, body *Grammar[TToken, TNodeKind], min, max int) *Grammar[TToken, TNodeKind] {
	m := max
	return Repeat(label, body, min, &m)
}

func Ref[TToken, TNodeKind comparable](label, target GrammarLabel) *Grammar[TToken, TNodeKind] {
	return &Grammar[TToken, TNodeKind]{
		GrammarLabel:    label,
		Kind:            GReference,
		ReferenceTarget: target,
	}
}

/*
GrammarIsTokenNode reports whether the node is a terminal token node (GToken).
*/
func GrammarIsTokenNode[TToken, TNodeKind comparable](n *Grammar[TToken, TNodeKind]) bool {
	return n != nil && n.Kind == GToken
}

/*
GrammarOptionalTokenChild returns the single token wrapped by an optional, if the node is GOptional with exactly one GToken child.

This is a shape predicate for tooling (e.g. includes); it is not the same as nullable in the grammar-analysis sense.
*/
func GrammarOptionalTokenChild[TToken, TNodeKind comparable](n *Grammar[TToken, TNodeKind]) (token TToken, ok bool) {
	if n == nil || n.Kind != GOptional || len(n.Children) != 1 || n.Children[0] == nil || n.Children[0].Kind != GToken {
		return token, false
	}
	return n.Children[0].Token, true
}
