package syntaxa

import (
	"strconv"
	"strings"
)

/*
GrammarKind denotes the algebraic operation represented by a grammar node.

The grammar IR is intentionally minimal and purely structural. Each kind
corresponds to a fundamental grammar combinator found in EBNF/PEG-style
grammars. Optional recovery metadata (RecoveryTokens, NoConsumeOnRecoveryTokens)
may be set on rule-root nodes for tooling and introspection; execution semantics
otherwise live in the parser engine.

Kinds:

  - GToken
    Atomic terminal symbol. Matches exactly one lexer token.

  - GConcat
    Sequential composition. All child grammars must match in order.

  - GChoice
    Alternation (union). Exactly one child grammar must match.

  - GRepeat
    Repetition operator. The single child grammar is matched multiple
    times according to Min/Max bounds.

  - GOptional
    Optional operator. Equivalent to GRepeat with Min=0 and Max=1,
    but preserved explicitly for clarity and tooling.

  - GEpsilon
    Empty production. Always succeeds without consuming input.

This algebra is closed and intentionally small. Any higher-level grammar
constructs (lists, blocks, separators, precedence rules, etc.) must compile
down into these primitives rather than extending the IR.

Execution semantics, error recovery, AST construction, and contextual logic
are handled by the parser engine, not by the grammar IR itself.
*/
//go:generate stringer -type GrammarKind
type GrammarKind uint8

const (
	GToken GrammarKind = iota + 1
	GConcat
	GChoice
	GRepeat
	GOptional
	GEpsilon
	GNest
)

/*
RuleLabel is an optional human-readable label for a grammar rule.

Used for diagnostics and tooling; the canonical identifier for a rule is GrammarID.
*/
type RuleLabel string

/*
GrammarID uniquely identifies a grammar rule within a grammar package.

Used as the key in Rules maps and to reference the entry rule and nest owners.
*/
type GrammarID string

/*
NodePath is a dot-separated path from the rule root to a node (e.g. "0", "0.1", "0.2.0").

Generated by FinalizeNodePaths and used as part of NodeKey for analysis (Nullable, First, Follow).
*/
type NodePath string

/*
Grammar represents a node in the declarative grammar intermediate
representation.

The grammar forms a tree of composable combinators describing the syntactic
structure of a language. It is intentionally free of execution behavior and
serves as a canonical, introspectable description of the language grammar.

Field semantics depend on Kind:

  - GToken
    Token holds the terminal token value to be matched.
    Children, Min, and Max are unused.

  - GConcat, GChoice
    Children contains the ordered sub-grammars.
    Token, Min, and Max are unused.

  - GRepeat
    Children must contain exactly one grammar node (the repeated body).
    Min specifies the minimum number of repetitions.
    Max specifies the maximum number of repetitions.

  - nil indicates unbounded repetition.

  - GOptional
    Children must contain exactly one grammar node.
    Token, Min, and Max are unused.

  - GEpsilon
    Represents the empty production.
    All other fields are unused.

  - GNest
    OpenToken and CloseToken hold the bracket terminals; Children holds exactly one body grammar.
    Min and Max are unused.

  - Common
    GrammarID identifies the rule. RuleLabel is optional. NodePath is filled by FinalizeNodePaths.

  - Recovery (optional, for rule-root nodes)
    RecoveryTokens and NoConsumeOnRecoveryTokens describe the recovery boundaries for the rule
    that uses this node as its root. When set, the engine resyncs at those tokens on FailureError;
    NoConsumeOnRecoveryTokens are sync points where the token is left in the stream for the parent.
    Populated by ParserRuleCreate when a rule is created with this grammar.

Invariants:

  - GrammarKind determines which fields are semantically valid.
  - No grammar node may contain execution logic beyond optional recovery metadata.
  - Higher-level constructs must be expressed by composition, not by adding
    new GrammarKind values or special-case fields.

This structure enables grammar introspection, transformation, visualization,
pattern derivation, and parser execution from a single authoritative grammar
definition.
*/
type Grammar[TToken comparable] struct {
	GrammarID GrammarID

	/* Kind defines the grammar combinator represented by this node. */
	Kind GrammarKind

	/* Token is the terminal symbol matched by GToken nodes. */
	Token TToken

	OpenToken  *TToken
	CloseToken *TToken

	/* Children holds sub-grammars for composite operators (Concat, Choice, Repeat, Optional). */
	Children []*Grammar[TToken]

	/* Min is the minimum repetition count for GRepeat nodes. */
	Min int

	/* Max is the maximum repetition count for GRepeat nodes. Nil denotes unbounded repetition. */
	Max *int

	RuleLabel RuleLabel

	/* NodePath is assigned by FinalizeNodePaths; used as the key for analysis maps. */
	NodePath *NodePath

	/* IsContextBoundary is true only for the root node of a named production (e.g. from Rule.Root). Used by collectAll to populate the Rules map. */
	IsContextBoundary bool

	/*
		RecoveryTokens are sync tokens at which the engine resyncs on FailureError (consumes until one is seen).
		Set on the rule-root grammar by ParserRuleCreate. Nil when not applicable.
	*/
	RecoveryTokens []TToken

	/*
		NoConsumeOnRecoveryTokens are sync tokens at which recovery does not consume (token left in stream for parent).
		Set on the rule-root grammar by ParserRuleCreate. Nil when not applicable.
	*/
	NoConsumeOnRecoveryTokens []TToken
}

/*
FinalizeNodePaths assigns a unique NodePath to each node in the grammar tree.

Paths are dot-separated indices from the root (e.g. "0", "0.1", "0.2.0").
Idempotent: if NodePath is already set, the subtree is skipped.
Call this once before producing a grammar package or running analysis.
*/
func (g *Grammar[TToken]) FinalizeNodePaths() {
	if g == nil {
		return
	}

	if g.NodePath != nil {
		return
	}

	fillForGrammar(g, "0")
}

func fillForGrammar[TToken comparable](g *Grammar[TToken], current string) {
	if g == nil {
		return
	}

	// Assign current node's path.
	p := NodePath(current)
	g.NodePath = &p

	// Recurse into children with dot-separated indices.
	if len(g.Children) == 0 {
		return
	}

	// Small optimization to avoid repeated allocations in deep trees:
	// build "current." once and append indices.
	prefix := current + "."

	// Pre-size a builder for worst-case index string lengths.
	// Not strictly necessary, but keeps this cheap on large grammars.
	var sb strings.Builder
	sb.Grow(len(prefix) + 20)

	for i, child := range g.Children {
		if child == nil {
			continue
		}

		sb.Reset()
		sb.WriteString(prefix)
		sb.WriteString(strconv.Itoa(i))

		fillForGrammar(child, sb.String())
	}
}

/*
	IsRegular computes whether this grammar is regular.

Given the current Grammar algebra, all grammars are regular by construction.
This function exists for forward compatibility in case non-regular constructs
(e.g. recursive nonterminals) are introduced in the future.
*/
func (g *Grammar[TToken]) IsRegular() bool {
	if g == nil {
		return true
	}

	// Defensive cycle guard in case future extensions introduce references
	visited := make(map[*Grammar[TToken]]bool)

	var walk func(*Grammar[TToken]) bool
	walk = func(n *Grammar[TToken]) bool {
		if n == nil {
			return true
		}

		if visited[n] {
			// Cycles alone do NOT make a grammar non-regular
			// (Kleene star is cyclic by nature)
			return true
		}
		visited[n] = true

		switch n.Kind {
		case GToken, GEpsilon:
			return true

		case GConcat, GChoice:
			for _, c := range n.Children {
				if !walk(c) {
					return false
				}
			}
			return true

		case GRepeat, GOptional:
			if len(n.Children) != 1 {
				return false
			}
			return walk(n.Children[0])

		case GNest:
			return false
		default:
			// Unknown grammar kind => not provably regular
			return false
		}
	}

	return walk(g)
}

/*
MarkAsContextBoundary marks the grammar node as the root of a named production.

Called by the rule factory for nodes created by Rule.Root. collectAll uses this to decide which nodes to add to the Rules map.
*/
func MarkAsContextBoundary[TToken comparable](g *Grammar[TToken]) {
	if g != nil {
		g.IsContextBoundary = true
	}
}

/*
Token constructs an atomic terminal grammar node that matches exactly one token.
*/
func Token[TToken comparable](id GrammarID, tok TToken) *Grammar[TToken] {
	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GToken,
		Token:     tok,
	}
}

/*
Concat constructs a sequential composition of grammar nodes.

All children must match in order for the production to succeed.
At least one child must be provided.
*/
func Concat[TToken comparable](id GrammarID, children ...*Grammar[TToken]) *Grammar[TToken] {
	if len(children) == 0 {
		panic("Concat: at least one child grammar required")
	}

	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GConcat,
		Children:  children,
	}
}

/*
Nest constructs a bracketed grammar node that matches openToken, then body, then closeToken.

Use cases:
- Parenthesized expressions: ( expr )
- Block delimiters: { stmt* }
- Quote-enclosed strings: " ... "
- Any construct with balanced open/close terminals

Time complexity: O(1)
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- OpenToken and CloseToken are stored as pointers to the given token values

Edge cases:
- Panics if body is nil
*/
func Nest[TToken comparable](id GrammarID, openToken TToken, closeToken TToken, body *Grammar[TToken]) *Grammar[TToken] {
	return &Grammar[TToken]{
		GrammarID:  id,
		Kind:       GNest,
		Children:   []*Grammar[TToken]{body},
		OpenToken:  &openToken,
		CloseToken: &closeToken,
	}
}

/*
Choice constructs an alternation between grammar nodes.

Exactly one of the children must match.
At least one child must be provided.
*/
func Choice[TToken comparable](id GrammarID, children ...*Grammar[TToken]) *Grammar[TToken] {
	if len(children) == 0 {
		panic("Choice: at least one child grammar required")
	}

	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GChoice,
		Children:  children,
	}
}

/*
Repeat constructs a bounded or unbounded repetition grammar.

The body grammar is repeated between min and max times.

If max is nil, repetition is unbounded.

Invariants:
  - body must be non-nil
  - min must be >= 0
  - if max != nil, *max must be >= min
*/
func Repeat[TToken comparable](id GrammarID, body *Grammar[TToken], min int, max *int) *Grammar[TToken] {
	if body == nil {
		panic("Repeat: body grammar must not be nil")
	}
	if min < 0 {
		panic("Repeat: min must be >= 0")
	}
	if max != nil && *max < min {
		panic("Repeat: max must be >= min")
	}

	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GRepeat,
		Children:  []*Grammar[TToken]{body},
		Min:       min,
		Max:       max,
	}
}

/*
Optional constructs an optional grammar node.

Equivalent to Repeat(body, 0, 1) but preserved explicitly for semantic clarity.
*/
func Optional[TToken comparable](id GrammarID, body *Grammar[TToken]) *Grammar[TToken] {
	if body == nil {
		panic("Optional: body grammar must not be nil")
	}

	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GOptional,
		Children:  []*Grammar[TToken]{body},
	}
}

/*
Epsilon constructs an empty production grammar node.

This always succeeds without consuming input.
*/
func Epsilon[TToken comparable](id GrammarID) *Grammar[TToken] {
	return &Grammar[TToken]{
		GrammarID: id,
		Kind:      GEpsilon,
	}
}

/*
ZeroOrMore constructs an unbounded repetition with minimum 0.

Equivalent to Repeat(id, body, 0, nil). Matches the body zero or more times (Kleene star).

Use cases:
- Optional lists: item*
- Trailing separators: (elem ("," elem)*)
- Skippable whitespace or comments

Time complexity: O(1) for construction; matching is O(n) in input length
Space complexity: O(1)

Prerequisites:
- body must be non-nil (delegates to Repeat, which panics if body is nil)

Edge cases:
- Can succeed without consuming input (zero repetitions)
*/
func ZeroOrMore[TToken comparable](id GrammarID, body *Grammar[TToken]) *Grammar[TToken] {
	return Repeat(id, body, 0, nil)
}

/*
OneOrMore constructs an unbounded repetition with minimum 1.

Equivalent to Repeat(id, body, 1, nil). Matches the body one or more times (positive closure).

Use cases:
- Non-empty lists: item+
- Required sequences: digit+
- At least one occurrence of a sub-grammar

Time complexity: O(1) for construction; matching is O(n) in input length
Space complexity: O(1)

Prerequisites:
- body must be non-nil (delegates to Repeat, which panics if body is nil)

Edge cases:
- Fails if no occurrence of body matches (unlike ZeroOrMore)
*/
func OneOrMore[TToken comparable](id GrammarID, body *Grammar[TToken]) *Grammar[TToken] {
	return Repeat(id, body, 1, nil)
}

/*
Exactly constructs a repetition that must occur exactly n times.

Equivalent to Repeat(id, body, n, &n). The body must match precisely n times.

Use cases:
- Fixed-width fields: exactly 4 digits for a year
- Tuple-like structures: (a, b, c)
- Repetition with both lower and upper bound equal

Time complexity: O(1) for construction; matching is O(n) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- n must be >= 0 (Repeat enforces min >= 0 and max >= min)

Edge cases:
- Panics if body is nil or n < 0 (via Repeat)
- Fails if fewer or more than n matches occur
*/
func Exactly[TToken comparable](id GrammarID, body *Grammar[TToken], n int) *Grammar[TToken] {
	max := n
	return Repeat(id, body, n, &max)
}

/*
AtMost constructs a repetition with no minimum and a fixed maximum.

Equivalent to Repeat(id, body, 0, &max). Matches the body zero up to max times inclusive.

Use cases:
- Bounded optional lists: at most N items
- Length-limited sequences: up to 8 hex digits
- Cap on repetition to avoid runaway matching

Time complexity: O(1) for construction; matching is O(max) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- max must be >= 0 (Repeat requires max >= min; min is 0)

Edge cases:
- Panics if body is nil or max < 0 (via Repeat)
- Succeeds with zero matches; fails only if more than max matches would be required
*/
func AtMost[TToken comparable](id GrammarID, body *Grammar[TToken], max int) *Grammar[TToken] {
	return Repeat(id, body, 0, &max)
}

/*
Between constructs a repetition bounded inclusively between min and max.

Equivalent to Repeat(id, body, min, &max). The body must match at least min times and at most max times.

Use cases:
- Bounded lists: between 1 and 10 items
- Length range constraints: 2 to 4 hex digits
- Repetition with both lower and upper bounds

Time complexity: O(1) for construction; matching is O(max) in repetitions
Space complexity: O(1)

Prerequisites:
- body must be non-nil
- min must be >= 0
- max must be >= min

Edge cases:
- Panics if body is nil, min < 0, or max < min (via Repeat)
- Fails if fewer than min or more than max matches occur
*/
func Between[TToken comparable](id GrammarID, body *Grammar[TToken], min, max int) *Grammar[TToken] {
	m := max
	return Repeat(id, body, min, &m)
}

/*
GrammarIsTokenNode reports whether the node is a terminal token node (GToken).
*/
func GrammarIsTokenNode[TToken comparable](n *Grammar[TToken]) bool {
	return n != nil && n.Kind == GToken
}

/*
GrammarOptionalTokenChild returns the single token wrapped by an optional, if the node is GOptional with exactly one GToken child.

This is a shape predicate for tooling (e.g. includes); it is not the same as nullable in the grammar-analysis sense.
*/
func GrammarOptionalTokenChild[TToken comparable](n *Grammar[TToken]) (token TToken, ok bool) {
	if n == nil || n.Kind != GOptional || len(n.Children) != 1 || n.Children[0] == nil || n.Children[0].Kind != GToken {
		return token, false
	}
	return n.Children[0].Token, true
}
